[package]
name = "nxcloud"
version = "0.1.0"
authors = ["Ethan Budd <budde25@protonmail.com>"]
description = "A client for interacting with your NextCloud server"
readme = "README.md"
license = "GPL-3.0-or-later"
edition = "2018"
keywords = ["NextCloud", "CLI", "utilities"]
categories = ["command-line-utilities"]
homepage = "https://github.com/budde25/nextcloud-client-cli"
repository = "https://github.com/budde25/nextcloud-client-cli"

[dependencies]

structopt = "0.3.18"
url = "2.1.1"
reqwest = { version = "0.10.8", features = ["json"] }
tokio = { version = "0.2.22", features = ["full"] }
xmltree = "0.10.1"
bytes = "0.5.6"
base64 = "0.13.0"
keyring = "0.9.0"
path-dedot = "3.0.7"
path-absolutize = "3.0.6"
anyhow = "1.0"