[package]
name = "nxcloud"
version = "0.2.1"
authors = ["Ethan Budd <budde25@protonmail.com>"]
description = "A client for interacting with your NextCloud server"
readme = "README.md"
license = "MIT OR Apache-2.0"
edition = "2018"
keywords = ["NextCloud", "CLI", "utilities"]
categories = ["command-line-utilities"]
homepage = "https://github.com/budde25/nextcloud-client-cli"
repository = "https://github.com/budde25/nextcloud-client-cli"

[dependencies]

structopt = "0.3"
url = "2.2"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.1", features = ["full"] }
xmltree = "0.10"
bytes = "1.0"
base64 = "0.13"
keyring = "0.10"
path-dedot = "3.0"
path-absolutize = "3.0"
anyhow = "1.0"
lazy_static = "1.4"
env_logger = "0.8"
clap = "2.33"
log = "0.4"
rustyline = "7.1"
dirs = "3.0"