[package]
name = "nextcloudcli"
version = "0.1.0"
authors = ["budde25 <budde25@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

structopt = "0.3.16"
url = "2.1.1"
reqwest = { version = "0.10.7", features = ["json"] }
tokio = { version = "0.2.22", features = ["full"] }
xmltree = "0.10.1"
bytes = "0.5.6"